# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adjust_data_n.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Adjust_Exp_Data(QtWidgets.QDialog):
    def __init__(self):
        super(Adjust_Exp_Data, self).__init__()
        self.init_ui()

    def init_ui(self):
        self.resize(247, 244)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self)
        self.label.setMinimumSize(QtCore.QSize(237, 22))
        self.label.setMaximumSize(QtCore.QSize(237, 22))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setMinimumSize(QtCore.QSize(0, 120))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(3, 0, 3, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(105, 24))
        self.label_3.setMaximumSize(QtCore.QSize(105, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.box_smooth = QtWidgets.QSpinBox(self.frame)
        self.box_smooth.setMinimumSize(QtCore.QSize(100, 0))
        self.box_smooth.setMaximumSize(QtCore.QSize(100, 16777215))
        self.box_smooth.setMinimum(1)
        self.box_smooth.setMaximum(10)
        self.box_smooth.setObjectName("box_smooth")
        self.gridLayout.addWidget(self.box_smooth, 1, 1, 1, 1)
        self.shift_x = QtWidgets.QDoubleSpinBox(self.frame)
        self.shift_x.setMinimumSize(QtCore.QSize(100, 0))
        self.shift_x.setMaximumSize(QtCore.QSize(100, 16777215))
        self.shift_x.setMinimum(-20.0)
        self.shift_x.setMaximum(20.0)
        self.shift_x.setSingleStep(0.1)
        self.shift_x.setObjectName("shift_x")
        self.gridLayout.addWidget(self.shift_x, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(105, 24))
        self.label_4.setMaximumSize(QtCore.QSize(105, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.bg_slope = QtWidgets.QDoubleSpinBox(self.frame)
        self.bg_slope.setMinimumSize(QtCore.QSize(100, 0))
        self.bg_slope.setMaximumSize(QtCore.QSize(100, 16777215))
        self.bg_slope.setMinimum(-1.0)
        self.bg_slope.setMaximum(1.0)
        self.bg_slope.setSingleStep(0.1)
        self.bg_slope.setObjectName("bg_slope")
        self.gridLayout.addWidget(self.bg_slope, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(105, 24))
        self.label_2.setMaximumSize(QtCore.QSize(105, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setMinimumSize(QtCore.QSize(105, 24))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.frame_2 = QtWidgets.QFrame(self)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMinimumSize(QtCore.QSize(105, 0))
        self.label_5.setMaximumSize(QtCore.QSize(105, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.aphase = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.aphase.setMinimumSize(QtCore.QSize(100, 0))
        self.aphase.setMaximumSize(QtCore.QSize(100, 16777215))
        self.aphase.setMaximum(1.0)
        self.aphase.setSingleStep(0.1)
        self.aphase.setObjectName("aphase")
        self.horizontalLayout.addWidget(self.aphase)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.show()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Adjust_Exp_Data", "Dialog"))
        self.label.setText(_translate("Adjust_Exp_Data", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">ADJUST EXP. DATA</span></p></body></html>"))
        self.label_3.setText(_translate("Adjust_Exp_Data", "<html><head/><body><p><span style=\" font-size:16pt;\">BG SLOPE</span></p></body></html>"))
        self.label_4.setText(_translate("Adjust_Exp_Data", "<html><head/><body><p><span style=\" font-size:16pt;\">SHIFT X AXIS</span></p></body></html>"))
        self.label_2.setText(_translate("Adjust_Exp_Data", "<html><head/><body><p><span style=\" font-size:16pt;\">BOX Smth.</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Adjust_Exp_Data", "Ref. Exp."))
        self.comboBox.setItemText(1, _translate("Adjust_Exp_Data", "RCs Exp."))
        self.label_7.setText(_translate("Adjust_Exp_Data", "<html><head/><body><p><span style=\" font-size:16pt;\">Data Type</span></p></body></html>"))
        self.label_6.setText(_translate("Adjust_Exp_Data", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Sim. RC Phase</span></p></body></html>"))
        self.label_5.setText(_translate("Adjust_Exp_Data", "<html><head/><body><p><span style=\" font-size:16pt;\">APHASE (π)</span></p></body></html>"))


