# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KLDD_layout_n.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 684)
        MainWindow.setMinimumSize(QtCore.QSize(805, 684))
        MainWindow.setMaximumSize(QtCore.QSize(805, 684))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.KLDD_widget = QtWidgets.QWidget(MainWindow)
        self.KLDD_widget.setMinimumSize(QtCore.QSize(805, 639))
        self.KLDD_widget.setMaximumSize(QtCore.QSize(805, 640))
        self.KLDD_widget.setObjectName("KLDD_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.KLDD_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.KLDD_widget)
        self.frame_3.setMinimumSize(QtCore.QSize(490, 300))
        self.frame_3.setMaximumSize(QtCore.QSize(490, 300))
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_7 = QtWidgets.QWidget(self.frame_3)
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.widget_7)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.push_simu_REF = QtWidgets.QPushButton(self.widget_7)
        self.push_simu_REF.setMinimumSize(QtCore.QSize(100, 30))
        self.push_simu_REF.setMaximumSize(QtCore.QSize(100, 30))
        self.push_simu_REF.setAutoFillBackground(True)
        self.push_simu_REF.setObjectName("push_simu_REF")
        self.horizontalLayout_3.addWidget(self.push_simu_REF)
        self.bt_load_ref = QtWidgets.QPushButton(self.widget_7)
        self.bt_load_ref.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_load_ref.setMaximumSize(QtCore.QSize(120, 30))
        self.bt_load_ref.setObjectName("bt_load_ref")
        self.horizontalLayout_3.addWidget(self.bt_load_ref)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget_7)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.KLDD_widget)
        self.widget_14.setMinimumSize(QtCore.QSize(250, 300))
        self.widget_14.setMaximumSize(QtCore.QSize(270, 300))
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.widget_14)
        self.frame_6.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(270, 70))
        self.frame_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setLineWidth(1)
        self.frame_6.setMidLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setMinimumSize(QtCore.QSize(0, 27))
        self.label.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setWordWrap(True)
        self.label.setIndent(0)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.widget_5 = QtWidgets.QWidget(self.frame_6)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 35))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.show_load = QtWidgets.QLineEdit(self.widget_5)
        self.show_load.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.show_load.setAlignment(QtCore.Qt.AlignCenter)
        self.show_load.setObjectName("show_load")
        self.horizontalLayout.addWidget(self.show_load)
        self.browse_file = QtWidgets.QPushButton(self.widget_5)
        self.browse_file.setObjectName("browse_file")
        self.horizontalLayout.addWidget(self.browse_file)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(self.widget_14)
        self.frame.setMinimumSize(QtCore.QSize(250, 0))
        self.frame.setMaximumSize(QtCore.QSize(270, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.widget_6 = QtWidgets.QWidget(self.frame)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Bragg_h = QtWidgets.QLineEdit(self.widget_6)
        self.Bragg_h.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Bragg_h.setAlignment(QtCore.Qt.AlignCenter)
        self.Bragg_h.setObjectName("Bragg_h")
        self.horizontalLayout_2.addWidget(self.Bragg_h)
        self.Bragg_k = QtWidgets.QLineEdit(self.widget_6)
        self.Bragg_k.setAlignment(QtCore.Qt.AlignCenter)
        self.Bragg_k.setObjectName("Bragg_k")
        self.horizontalLayout_2.addWidget(self.Bragg_k)
        self.Bragg_l = QtWidgets.QLineEdit(self.widget_6)
        self.Bragg_l.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Bragg_l.setAlignment(QtCore.Qt.AlignCenter)
        self.Bragg_l.setObjectName("Bragg_l")
        self.horizontalLayout_2.addWidget(self.Bragg_l)
        self.Bragg_k.raise_()
        self.Bragg_l.raise_()
        self.Bragg_h.raise_()
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_9 = QtWidgets.QWidget(self.frame)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 17))
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.widget_9)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.widget_9)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setIndent(0)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.frame)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 23))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 22))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.photon_energy = QtWidgets.QLineEdit(self.widget_10)
        self.photon_energy.setMinimumSize(QtCore.QSize(105, 21))
        self.photon_energy.setAlignment(QtCore.Qt.AlignCenter)
        self.photon_energy.setPlaceholderText("eV")
        self.photon_energy.setObjectName("photon_energy")
        self.horizontalLayout_8.addWidget(self.photon_energy)
        self.choose_mode = QtWidgets.QComboBox(self.widget_10)
        self.choose_mode.setMinimumSize(QtCore.QSize(110, 27))
        self.choose_mode.setStatusTip("")
        self.choose_mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.choose_mode.setObjectName("choose_mode")
        self.choose_mode.addItem("")
        self.choose_mode.addItem("")
        self.horizontalLayout_8.addWidget(self.choose_mode)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.widget_11 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.range_start = QtWidgets.QLineEdit(self.widget_11)
        self.range_start.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.range_start.setAlignment(QtCore.Qt.AlignCenter)
        self.range_start.setObjectName("range_start")
        self.horizontalLayout_5.addWidget(self.range_start)
        self.range_end = QtWidgets.QLineEdit(self.widget_11)
        self.range_end.setAlignment(QtCore.Qt.AlignCenter)
        self.range_end.setObjectName("range_end")
        self.horizontalLayout_5.addWidget(self.range_end)
        self.step_size = QtWidgets.QLineEdit(self.widget_11)
        self.step_size.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.step_size.setAlignment(QtCore.Qt.AlignCenter)
        self.step_size.setObjectName("step_size")
        self.horizontalLayout_5.addWidget(self.step_size)
        self.verticalLayout_4.addWidget(self.widget_11)
        self.widget_13 = QtWidgets.QWidget(self.frame)
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.widget_13)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.label_2 = QtWidgets.QLabel(self.widget_13)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.verticalLayout_4.addWidget(self.widget_13)
        self.widget_12 = QtWidgets.QWidget(self.frame)
        self.widget_12.setMinimumSize(QtCore.QSize(100, 25))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.polar_angle = QtWidgets.QLineEdit(self.widget_12)
        self.polar_angle.setMinimumSize(QtCore.QSize(105, 21))
        self.polar_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.polar_angle.setObjectName("polar_angle")
        self.horizontalLayout_6.addWidget(self.polar_angle)
        self.take_off_angle = QtWidgets.QLineEdit(self.widget_12)
        self.take_off_angle.setMinimumSize(QtCore.QSize(105, 21))
        self.take_off_angle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.take_off_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.take_off_angle.setObjectName("take_off_angle")
        self.horizontalLayout_6.addWidget(self.take_off_angle)
        self.verticalLayout_4.addWidget(self.widget_12)
        self.verticalLayout_7.addWidget(self.frame)
        self.gridLayout.addWidget(self.widget_14, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.KLDD_widget)
        self.widget_2.setMinimumSize(QtCore.QSize(250, 300))
        self.widget_2.setMaximumSize(QtCore.QSize(270, 300))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.widget_2)
        self.frame_7.setMinimumSize(QtCore.QSize(250, 60))
        self.frame_7.setMaximumSize(QtCore.QSize(270, 60))
        self.frame_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_7.setLineWidth(1)
        self.frame_7.setMidLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_15 = QtWidgets.QWidget(self.frame_7)
        self.widget_15.setMinimumSize(QtCore.QSize(0, 35))
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.widget_15)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_10.setSizeIncrement(QtCore.QSize(0, 27))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.verticalLayout_8.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(self.frame_7)
        self.widget_16.setMinimumSize(QtCore.QSize(100, 25))
        self.widget_16.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.DWF = QtWidgets.QLineEdit(self.widget_16)
        self.DWF.setMinimumSize(QtCore.QSize(105, 21))
        self.DWF.setAlignment(QtCore.Qt.AlignCenter)
        self.DWF.setObjectName("DWF")
        self.horizontalLayout_10.addWidget(self.DWF)
        self.sigma = QtWidgets.QLineEdit(self.widget_16)
        self.sigma.setMinimumSize(QtCore.QSize(105, 21))
        self.sigma.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sigma.setAlignment(QtCore.Qt.AlignCenter)
        self.sigma.setObjectName("sigma")
        self.horizontalLayout_10.addWidget(self.sigma)
        self.verticalLayout_8.addWidget(self.widget_16)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(5)
        self.formLayout.setVerticalSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setMinimumSize(QtCore.QSize(123, 21))
        self.label_13.setMaximumSize(QtCore.QSize(123, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setMinimumSize(QtCore.QSize(123, 21))
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.unit_cell_spinBox = QtWidgets.QSpinBox(self.widget)
        self.unit_cell_spinBox.setMinimumSize(QtCore.QSize(115, 24))
        self.unit_cell_spinBox.setMaximumSize(QtCore.QSize(130, 24))
        self.unit_cell_spinBox.setWrapping(True)
        self.unit_cell_spinBox.setMaximum(99)
        self.unit_cell_spinBox.setProperty("value", 1)
        self.unit_cell_spinBox.setObjectName("unit_cell_spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.unit_cell_spinBox)
        self.IMFP_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.IMFP_lineEdit.setMinimumSize(QtCore.QSize(123, 21))
        self.IMFP_lineEdit.setMaximumSize(QtCore.QSize(123, 21))
        self.IMFP_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.IMFP_lineEdit.setObjectName("IMFP_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.IMFP_lineEdit)
        self.verticalLayout_3.addWidget(self.widget)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.widget_21 = QtWidgets.QWidget(self.frame_2)
        self.widget_21.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_21.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_21.setObjectName("widget_21")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_21)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.widget_21)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 1, 1, 1)
        self.input_atom_2 = QtWidgets.QLineEdit(self.widget_21)
        self.input_atom_2.setMinimumSize(QtCore.QSize(65, 0))
        self.input_atom_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.input_atom_2.setMaxLength(8)
        self.input_atom_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_atom_2.setObjectName("input_atom_2")
        self.gridLayout_3.addWidget(self.input_atom_2, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_21)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.input_atom_1 = QtWidgets.QLineEdit(self.widget_21)
        self.input_atom_1.setMinimumSize(QtCore.QSize(65, 0))
        self.input_atom_1.setMaximumSize(QtCore.QSize(90, 16777215))
        self.input_atom_1.setMaxLength(8)
        self.input_atom_1.setAlignment(QtCore.Qt.AlignCenter)
        self.input_atom_1.setObjectName("input_atom_1")
        self.gridLayout_3.addWidget(self.input_atom_1, 1, 0, 1, 1)
        self.input_atom_3 = QtWidgets.QLineEdit(self.widget_21)
        self.input_atom_3.setMinimumSize(QtCore.QSize(65, 0))
        self.input_atom_3.setMaximumSize(QtCore.QSize(90, 16777215))
        self.input_atom_3.setMaxLength(8)
        self.input_atom_3.setAlignment(QtCore.Qt.AlignCenter)
        self.input_atom_3.setObjectName("input_atom_3")
        self.gridLayout_3.addWidget(self.input_atom_3, 3, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_21)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.frame_8 = QtWidgets.QFrame(self.widget_2)
        self.frame_8.setMinimumSize(QtCore.QSize(250, 65))
        self.frame_8.setMaximumSize(QtCore.QSize(270, 65))
        self.frame_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_8.setLineWidth(1)
        self.frame_8.setMidLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_18 = QtWidgets.QWidget(self.frame_8)
        self.widget_18.setMinimumSize(QtCore.QSize(0, 35))
        self.widget_18.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.widget_18)
        self.label_12.setMinimumSize(QtCore.QSize(0, 27))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_12.setSizeIncrement(QtCore.QSize(0, 30))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.verticalLayout_9.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.frame_8)
        self.widget_19.setMinimumSize(QtCore.QSize(100, 33))
        self.widget_19.setMaximumSize(QtCore.QSize(16777215, 33))
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.save_REF_txt = QtWidgets.QPushButton(self.widget_19)
        self.save_REF_txt.setMinimumSize(QtCore.QSize(32, 32))
        self.save_REF_txt.setObjectName("save_REF_txt")
        self.horizontalLayout_14.addWidget(self.save_REF_txt)
        self.save_RC_txt = QtWidgets.QPushButton(self.widget_19)
        self.save_RC_txt.setMinimumSize(QtCore.QSize(32, 32))
        self.save_RC_txt.setObjectName("save_RC_txt")
        self.horizontalLayout_14.addWidget(self.save_RC_txt)
        self.verticalLayout_9.addWidget(self.widget_19)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.KLDD_widget)
        self.frame_4.setMinimumSize(QtCore.QSize(490, 300))
        self.frame_4.setMaximumSize(QtCore.QSize(490, 300))
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_8 = QtWidgets.QWidget(self.frame_4)
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.widget_8)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.push_simu_RC = QtWidgets.QPushButton(self.widget_8)
        self.push_simu_RC.setMinimumSize(QtCore.QSize(100, 30))
        self.push_simu_RC.setMaximumSize(QtCore.QSize(100, 30))
        self.push_simu_RC.setObjectName("push_simu_RC")
        self.horizontalLayout_4.addWidget(self.push_simu_RC)
        self.bt_load_rc = QtWidgets.QPushButton(self.widget_8)
        self.bt_load_rc.setMinimumSize(QtCore.QSize(120, 30))
        self.bt_load_rc.setMaximumSize(QtCore.QSize(120, 30))
        self.bt_load_rc.setObjectName("bt_load_rc")
        self.horizontalLayout_4.addWidget(self.bt_load_rc)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.KLDD_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionLOAD = QtWidgets.QAction(MainWindow)
        self.actionLOAD.setObjectName("actionLOAD")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KLDD"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#000080;\">Reflectivities</span></p></body></html>"))
        self.push_simu_REF.setText(_translate("MainWindow", "SIMULATE"))
        self.bt_load_ref.setText(_translate("MainWindow", "LOAD EXP REF"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#000000;\">Load Material Information</span></p></body></html>"))
        self.show_load.setPlaceholderText(_translate("MainWindow", "Loaded File"))
        self.browse_file.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Bragg Reflection (</span><span style=\" font-size:16pt; font-style:italic;\">h</span><span style=\" font-size:16pt;\">, </span><span style=\" font-size:16pt; font-style:italic;\">k</span><span style=\" font-size:16pt;\">, </span><span style=\" font-size:16pt; font-style:italic;\">l </span><span style=\" font-size:16pt;\">)</span></p></body></html>"))
        self.Bragg_h.setPlaceholderText(_translate("MainWindow", "h"))
        self.Bragg_k.setPlaceholderText(_translate("MainWindow", "k"))
        self.Bragg_l.setPlaceholderText(_translate("MainWindow", "l"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Photon Energy</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Scan Mode</span></p></body></html>"))
        self.choose_mode.setItemText(0, _translate("MainWindow", "Angular"))
        self.choose_mode.setItemText(1, _translate("MainWindow", "Photonic"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Simulation Range (deg/eV)</span></p></body></html>"))
        self.range_start.setPlaceholderText(_translate("MainWindow", "Start"))
        self.range_end.setPlaceholderText(_translate("MainWindow", "End"))
        self.step_size.setPlaceholderText(_translate("MainWindow", "Step Size"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Polar Angle</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Take-off Angle</span></p></body></html>"))
        self.polar_angle.setPlaceholderText(_translate("MainWindow", "deg"))
        self.take_off_angle.setPlaceholderText(_translate("MainWindow", "deg"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#000000;\">Gaussian broaden</span></p></body></html>"))
        self.DWF.setPlaceholderText(_translate("MainWindow", "Debye-Waller Fac."))
        self.sigma.setPlaceholderText(_translate("MainWindow", "Sigma"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\"> &#xa0;&#xa0;# Unit Cells</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">IMFP (<span>&#8491;</span>)</span></p></body></html>"))
        self.label_16.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#0000ff;\">Select One or Multiple Atomic Species to Group</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">RCs Group</span></p></body></html>"))
        self.input_atom_2.setPlaceholderText(_translate("MainWindow", "species 2"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Name</span></p></body></html>"))
        self.input_atom_1.setPlaceholderText(_translate("MainWindow", "species 1"))
        self.input_atom_3.setPlaceholderText(_translate("MainWindow", "species 3"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#000000;\">Save Simulations (.txt)</span></p></body></html>"))
        self.save_REF_txt.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.save_REF_txt.setText(_translate("MainWindow", "SAVE REFs"))
        self.save_RC_txt.setText(_translate("MainWindow", "SAVE RCs"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#000080;\">Rocking Curves</span></p></body></html>"))
        self.push_simu_RC.setText(_translate("MainWindow", "SIMULATE"))
        self.bt_load_rc.setText(_translate("MainWindow", "LOAD EXP RCs"))
        self.actionLOAD.setText(_translate("MainWindow", "LOAD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

